environment:
  CMAKE_INSTALL_PATH: C:\cmake-install
  MINGW_PATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  ZLIB_VERSION: zlib-1.2.11
  CURL_VERSION: curl-7.63.0
install:
  - set PATH=%CMAKE_INSTALL_PATH%\bin;%CMAKE_INSTALL_PATH%\lib;%MINGW_PATH%\bin;%PATH%
  - appveyor DownloadFile "https://www.zlib.net/%ZLIB_VERSION%.tar.gz"
  - 7z x -o. %ZLIB_VERSION%.tar.gz
  - 7z x -oC:\cmake-install %ZLIB_VERSION%.tar
  - cd %CMAKE_INSTALL_PATH%\%ZLIB_VERSION%
  - cmake -H. -Bbuild -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL_PATH% -DCMAKE_SH="CMAKE_SH-NOTFOUND"
  - cmake --build build -- -j %NUMBER_OF_PROCESSORS%
  - cmake --build build --target install
  - appveyor DownloadFile "https://curl.haxx.se/download/%CURL_VERSION%.tar.gz"
  - 7z x -o. %CURL_VERSION%.tar.gz
  - 7z x -o%CMAKE_INSTALL_PATH% %CURL_VERSION%.tar
  - cd %CMAKE_INSTALL_PATH%\%CURL_VERSION%
  - cmake -H. -Bbuild -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL_PATH% -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF -DCMAKE_USE_WINSSL=ON -DCMAKE_SH="CMAKE_SH-NOTFOUND"
  - cmake --build build -- -j %NUMBER_OF_PROCESSORS%
  - cmake --build build --target install
  - cd C:\projects\tangram-es
before_build:
  - git submodule update --init --recursive
build_script:
  - mingw32-make windows -j %NUMBER_OF_PROCESSORS% CMAKE_OPTIONS="-DCURL_LIBRARIES=%CMAKE_INSTALL_PATH%/bin/libcurl.dll -DCURL_INCLUDE_DIRS=C:/cmake-install/include"
